### ISSUE TITLE
Uncaught Type Error when opening the first time

### ISSUE THREAD

**Issue by Hurric4ne** [TheIronDeveloper/pokemon-sorter#2]
Hey Tyler,

i found a bug. Opening the site the first time i cant click on any buttons, following error appears in the Dev-Tools (chrome 54 only):

Uncaught TypeError: Cannot read property 'replace' of undefined (main.min.js:8)

Dev-Tool finds a uncaught Syntax Error: Unexpected token on line 8, Column 106208. Coudn't find out what's the problem though.

Sometimes a Reload is enough, sometimes i need to Cache-Reload (STRG+F5).

**Comment by TheIronDev** [comment]
Fixed, the issue was that I had the script tag at the top of the file. Because require.js is async, the page would load *sometimes*. Its a big performance no-no though, so moving the script tag to the bottom resolved it.
